task: detection

num_classes: 1
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: ./dataset/mot17/raw/
    ann_file: ./dataset/mot17/annotations/train.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 16
  num_workers: 4
  drop_last: True


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: ./dataset/mot17/raw/
    ann_file: ./dataset/mot17/annotations/val.json
    transforms:
      type: Compose
      ops: ~

  shuffle: False
  batch_size: 4
  num_workers: 4
  drop_last: False
